import { z } from "zod";

const optionalUrl = z.preprocess(
  (value) =>
    typeof value === "string" && value.trim() === "" ? undefined : value,
  z.string().url().optional(),
);
const publicPageSlugWithDefault = (fallback: string) =>
  z.preprocess((value) => {
    if (typeof value !== "string") return value;
    const slug = value.trim();
    if (!slug) return undefined;
    if (slug === "1") return "inicio";
    if (slug === "2") return "biblioteca";
    return slug;
  }, z.string().min(1).default(fallback));
const envSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().min(1).default("Corazón Migrante"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:4173"),
  NEXT_PUBLIC_API_BASE_URL: optionalUrl,
  NEXT_PUBLIC_PUBLIC_VIEW_SLUG: publicPageSlugWithDefault("inicio"),
  NEXT_PUBLIC_CMS_LIBRARY_SLUG: publicPageSlugWithDefault("biblioteca"),
  NEXT_PUBLIC_PUBLIC_VIEW_CODE: z.string().optional(),
  NEXT_PUBLIC_PUBLIC_VIEW_ENDPOINT: z.string().optional(),
  NEXT_PUBLIC_PUBLIC_VIEW_ELEMENT_ENDPOINT: z.string().optional(),
  NEXT_PUBLIC_PUBLIC_CONTACT_PHONE: z.string().optional(),
  NEXT_PUBLIC_FILE_SERVER_LOGO_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_AUTH_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_LANDING_HERO_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_THERAPY_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_FAMILY_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_LIBRARY_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_EDITORIAL_HERO_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_EDITORIAL_FALLBACK_IMAGE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_PUBLIC_ASSETS_BASE_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_SPECIALTIES_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_PROFESSIONS_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_COUNTRIES_CITIES_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_OCCUPATIONS_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_SYMPTOMS_URL: optionalUrl,
  NEXT_PUBLIC_FILE_SERVER_THERAPY_GOALS_URL: optionalUrl,
});

export const env = envSchema.parse({
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  NEXT_PUBLIC_PUBLIC_VIEW_SLUG: process.env.NEXT_PUBLIC_PUBLIC_VIEW_SLUG,
  NEXT_PUBLIC_CMS_LIBRARY_SLUG: process.env.NEXT_PUBLIC_CMS_LIBRARY_SLUG,
  NEXT_PUBLIC_PUBLIC_VIEW_CODE: process.env.NEXT_PUBLIC_PUBLIC_VIEW_CODE,
  NEXT_PUBLIC_PUBLIC_VIEW_ENDPOINT:
    process.env.NEXT_PUBLIC_PUBLIC_VIEW_ENDPOINT,
  NEXT_PUBLIC_PUBLIC_VIEW_ELEMENT_ENDPOINT:
    process.env.NEXT_PUBLIC_PUBLIC_VIEW_ELEMENT_ENDPOINT,
  NEXT_PUBLIC_PUBLIC_CONTACT_PHONE:
    process.env.NEXT_PUBLIC_PUBLIC_CONTACT_PHONE,
  NEXT_PUBLIC_FILE_SERVER_LOGO_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_LOGO_URL,
  NEXT_PUBLIC_FILE_SERVER_AUTH_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_AUTH_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_LANDING_HERO_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_LANDING_HERO_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_THERAPY_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_THERAPY_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_FAMILY_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_FAMILY_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_LIBRARY_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_LIBRARY_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_EDITORIAL_HERO_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_EDITORIAL_HERO_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_EDITORIAL_FALLBACK_IMAGE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_EDITORIAL_FALLBACK_IMAGE_URL,
  NEXT_PUBLIC_FILE_SERVER_PUBLIC_ASSETS_BASE_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_PUBLIC_ASSETS_BASE_URL,
  NEXT_PUBLIC_FILE_SERVER_SPECIALTIES_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_SPECIALTIES_URL,
  NEXT_PUBLIC_FILE_SERVER_PROFESSIONS_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_PROFESSIONS_URL,
  NEXT_PUBLIC_FILE_SERVER_COUNTRIES_CITIES_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_COUNTRIES_CITIES_URL,
  NEXT_PUBLIC_FILE_SERVER_OCCUPATIONS_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_OCCUPATIONS_URL,
  NEXT_PUBLIC_FILE_SERVER_SYMPTOMS_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_SYMPTOMS_URL,
  NEXT_PUBLIC_FILE_SERVER_THERAPY_GOALS_URL:
    process.env.NEXT_PUBLIC_FILE_SERVER_THERAPY_GOALS_URL,
});
