import { intro, orderedSteps } from "@/features/tutorial/catalog/helpers";
import { navGroupTutorialId, navTutorialId, TUTORIAL_TARGETS } from "@/features/tutorial/model/tutorial-targets";
import type { TutorialDefinition } from "@/features/tutorial/model/tutorial.types";

/**
 * Recorridos del panel administrativo.
 *
 * Cada tutorial declara el permiso del módulo que enseña, de modo que una cuenta que no
 * puede entrar en ese módulo tampoco ve su tutorial: el catálogo no es una puerta
 * trasera para descubrir funciones que el rol no tiene.
 */
export const ADMIN_TUTORIALS: TutorialDefinition[] = [
  {
    id: "admin-navegacion",
    version: "1.0.0",
    title: "El panel, de un vistazo",
    description: "Qué hay en cada bloque del menú administrativo y por dónde se empieza.",
    category: "navegacion",
    level: "basico",
    route: "/admin",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["admin:read"],
    estimatedMinutes: 4,
    required: true,
    autoStart: true,
    nextTutorialId: "admin-solicitudes",
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Bienvenida al panel",
        "Un recorrido rápido por las secciones clave para gestionar la plataforma. Puedes salir cuando quieras.",
      ),
      {
        id: "notificaciones",
        title: "Notificaciones",
        body: "Los eventos del sistema: nuevas citas, cambios de estado y registros de usuarios.",
        target: navTutorialId("/admin/notificaciones"),
        placement: "right",
        // En móvil el menú vive dentro del cajón: el motor lo abre antes de buscar.
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
        errorMessage: "No pudimos abrir el menú de navegación. Ábrelo con el botón ☰ y pulsa «Reintentar».",
      },
      {
        id: "solicitudes",
        title: "Citas de pacientes",
        body: "Las solicitudes que llegan desde el portal del paciente. Es el flujo diario del centro.",
        target: navTutorialId("/admin/solicitudes"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "usuarios",
        title: "Personas registradas",
        body: "Las cuentas de pacientes, terapeutas y personal, con su rol y su estado.",
        target: navTutorialId("/admin/usuarios"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "publicidad",
        title: "Publicidad",
        body: "Empresas anunciantes, ubicaciones, campañas y creativos, agrupados en este desplegable.",
        target: navGroupTutorialId("Publicidad"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
        autoAction: "abrir-menu",
      },
      {
        id: "publicaciones",
        title: "Contenido editorial",
        body: "Noticias, columnas y artículos, con sus categorías, etiquetas y autores.",
        target: navTutorialId("/admin/contenido/publicaciones"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "campana",
        title: "Avisos en tiempo real",
        body: "La campana marca los eventos sin leer sin que tengas que entrar en la sección.",
        target: TUTORIAL_TARGETS.campanaNotificaciones,
        placement: "bottom",
      },
      {
        id: "ayuda",
        title: "Centro de ayuda",
        body: "Todos los tutoriales del panel viven aquí, con tu progreso guardado.",
        target: navTutorialId("/admin/ayuda"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      intro("cierre", "Ya te ubicas", "Sigue con «Gestionar citas de pacientes»: es lo que más se usa a diario."),
    ),
  },

  {
    id: "admin-solicitudes",
    version: "1.0.0",
    title: "Gestionar citas de pacientes",
    description: "Revisar las solicitudes que llegan y confirmarlas o reprogramarlas.",
    category: "citas",
    level: "basico",
    route: "/admin/solicitudes",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["therapy:manage"],
    estimatedMinutes: 4,
    required: true,
    prerequisites: ["admin-navegacion"],
    nextTutorialId: "admin-agendar-cita",
    steps: orderedSteps(
      intro(
        "bienvenida",
        "El flujo diario",
        "Las solicitudes de cita llegan aquí. Este recorrido enseña a leerlas y gestionarlas sin cambiar nada.",
      ),
      {
        id: "filtros",
        title: "Filtra lo que necesitas",
        body: "Acota por estado o busca por paciente para no revisar toda la lista cada vez.",
        target: TUTORIAL_TARGETS.filtrosTabla,
        placement: "bottom",
        waitForMs: 8000,
      },
      {
        id: "listado",
        title: "Cada fila es una solicitud",
        body: "Verás paciente, terapeuta, fecha y estado. Desde las acciones de la fila se confirma o se ajusta.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Ahora mismo no hay solicitudes registradas, por eso el listado no aparece.",
      },
      intro(
        "cierre",
        "Con cuidado",
        "Cada cambio de estado avisa a la persona. Confirma solo cuando la agenda del terapeuta esté cerrada.",
      ),
    ),
  },

  {
    id: "admin-agendar-cita",
    version: "1.0.0",
    title: "Agendar una cita para un paciente",
    description: "Crear la cita desde el panel eligiendo paciente, terapeuta y disponibilidad real.",
    category: "citas",
    level: "intermedio",
    route: "/admin/booking",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["booking:create_for_patient"],
    estimatedMinutes: 4,
    prerequisites: ["admin-solicitudes"],
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Crear una cita",
        "Este es el registro más importante del sistema. Te acompañamos por el formulario sin enviar nada.",
      ),
      {
        id: "paciente",
        title: "Elige el paciente",
        body: "El desplegable solo muestra cuentas de paciente activas del sistema.",
        target: "#patientUserId",
        placement: "bottom",
        interactiveTarget: true,
        waitForMs: 8000,
        errorMessage: "El selector de paciente aún no cargó. Espera unos segundos y pulsa «Reintentar».",
      },
      {
        id: "servicio",
        title: "Elige el servicio",
        body: "El servicio determina la duración de la sesión y el precio que se registra.",
        target: "#productId",
        placement: "bottom",
        interaction: { kind: "seleccion" },
        interactiveTarget: true,
      },
      {
        id: "horario",
        title: "Disponibilidad real",
        body: "Los horarios salen de la agenda del terapeuta: si no aparece un hueco, es que no está libre.",
        target: "main form",
        placement: "top",
      },
      {
        id: "confirmar",
        title: "Confirmar la cita",
        body: "Este botón crea la cita y notifica a las personas implicadas. Revisa los datos antes de pulsarlo.",
        target: 'main form button[type="submit"]',
        placement: "top",
      },
      intro("cierre", "Nada se ha creado", "El tutorial no envía el formulario: la cita se crea solo cuando tú confirmas."),
    ),
  },

  {
    id: "admin-usuarios",
    version: "1.0.0",
    title: "Buscar y filtrar personas",
    description: "Usar el buscador, los filtros y la tabla para encontrar y revisar una cuenta.",
    category: "administracion",
    level: "basico",
    route: "/admin/usuarios",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["users:manage"],
    estimatedMinutes: 3,
    recommended: true,
    steps: orderedSteps(
      intro("bienvenida", "Personas registradas", "Pacientes, terapeutas y personal del centro, todos en esta pantalla."),
      {
        id: "acciones",
        title: "Acciones de la pantalla",
        body: "Desde la cabecera se crean cuentas nuevas y se abren las acciones generales del módulo.",
        target: TUTORIAL_TARGETS.accionesPagina,
        placement: "bottom",
        errorMessage: "Esta pantalla no tiene acciones en la cabecera para tu rol.",
      },
      {
        id: "filtros",
        title: "Busca y filtra",
        body: "Escribe parte del nombre o del correo para reducir la lista. Los filtros se combinan entre sí.",
        target: TUTORIAL_TARGETS.filtrosTabla,
        placement: "bottom",
        waitForMs: 8000,
      },
      {
        id: "tabla",
        title: "La tabla de resultados",
        body: "Cada fila muestra rol y estado, y ofrece las acciones disponibles sobre esa cuenta.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "No hay resultados que mostrar con los filtros actuales.",
      },
      intro("cierre", "Mismo patrón en todo el panel", "Buscador arriba, tabla debajo y paginación al pie: se repite en casi todos los módulos."),
    ),
  },

  {
    id: "admin-publicaciones",
    version: "1.0.0",
    title: "Publicar contenido editorial",
    description: "Redactar una publicación y llevarla de borrador a publicada.",
    category: "contenido",
    level: "intermedio",
    route: "/admin/contenido/publicaciones",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["public_content:manage"],
    estimatedMinutes: 5,
    steps: orderedSteps(
      intro("bienvenida", "Contenido editorial", "Noticias, columnas y artículos que se publican en el sitio público."),
      {
        id: "formulario",
        title: "Redacta la publicación",
        body: "Título, resumen, cuerpo, portada, categoría y etiquetas. También eliges dónde aparecerá.",
        target: "main form",
        placement: "top",
      },
      {
        id: "listado",
        title: "Tus publicaciones",
        body: "Desde el listado se guarda como borrador, se envía a revisión, se publica o se archiva.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Todavía no hay publicaciones creadas.",
      },
      intro("cierre", "Revisa antes de publicar", "Lo publicado es visible para cualquier persona en el sitio público."),
    ),
  },

  {
    id: "admin-publicidad",
    version: "1.0.0",
    title: "Campañas publicitarias",
    description: "Cómo se relacionan empresas, ubicaciones, campañas y creativos.",
    category: "publicidad",
    level: "avanzado",
    route: "/admin/publicidad/campanas",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["public_content:manage"],
    estimatedMinutes: 5,
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Cómo encaja la publicidad",
        "Una empresa contrata una campaña, la campaña ocupa ubicaciones y muestra creativos. Ese es el orden.",
      ),
      {
        id: "formulario",
        title: "Crear una campaña",
        body: "Elige empresa, fechas, ubicaciones y las publicaciones o páginas donde debe aparecer.",
        target: "main form",
        placement: "top",
      },
      {
        id: "listado",
        title: "Gestiona lo activo",
        body: "Cada fila muestra el estado. Activar o pausar tiene efecto inmediato en el sitio público.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Aún no hay campañas registradas.",
      },
      intro("cierre", "Antes de crear una campaña", "Necesitas la empresa registrada y las ubicaciones configuradas."),
    ),
  },

  {
    id: "admin-descargables",
    version: "1.0.0",
    title: "Publicar descargables",
    description: "Guías y recursos con visibilidad, versiones y métricas de descarga.",
    category: "contenido",
    level: "intermedio",
    route: "/admin/descargables",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["public_content:manage"],
    estimatedMinutes: 4,
    steps: orderedSteps(
      intro("bienvenida", "Descargables", "Recursos con control de visibilidad: público, premium o de compra."),
      {
        id: "metricas",
        title: "Métricas y alta",
        body: "La cabecera resume totales, publicados, premium y descargas, y ofrece crear uno nuevo.",
        target: TUTORIAL_TARGETS.encabezadoPagina,
        placement: "bottom",
      },
      {
        id: "listado",
        title: "Versiones e historial",
        body: "Cada recurso publica versiones inmutables: al subir una nueva, la anterior queda en el historial.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Todavía no hay descargables publicados.",
      },
      intro("cierre", "Cuidado con la visibilidad", "Un recurso marcado como público es accesible sin iniciar sesión."),
    ),
  },

  {
    id: "admin-notificaciones",
    version: "1.0.0",
    title: "Ponerte al día con las notificaciones",
    description: "Filtrar los eventos del sistema y marcarlos como leídos.",
    category: "administracion",
    level: "basico",
    route: "/admin/notificaciones",
    roles: ["ADMIN", "SUPER_ADMIN"],
    permissions: ["admin:read"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "Todo lo que pasó", "Nuevas citas, cambios de estado y registros de usuarios, en orden."),
      {
        id: "acciones",
        title: "Filtra y marca como leído",
        body: "Cambia entre todas y solo las no leídas, y ponte al día de una vez con «Marcar todo como leído».",
        target: TUTORIAL_TARGETS.accionesPagina,
        placement: "bottom",
        errorMessage: "Las acciones aparecen cuando hay notificaciones registradas.",
      },
      {
        id: "listado",
        title: "El detalle de cada evento",
        body: "Cada fila enlaza con la pantalla donde ocurrió, para que puedas actuar sin buscarla.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "No hay notificaciones registradas ahora mismo.",
      },
      intro("cierre", "Listo", "La campana del menú te avisa sin necesidad de entrar aquí."),
    ),
  },

  {
    id: "contabilidad-introduccion",
    version: "1.0.0",
    title: "Contabilidad del centro",
    description: "Cuentas, grupos, centros de costo y transacciones: el control del dinero.",
    category: "contabilidad",
    level: "avanzado",
    route: "/admin/contabilidad",
    roles: ["SUPER_ADMIN", "CONTADOR"],
    permissions: ["accounting:read"],
    estimatedMinutes: 4,
    required: true,
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Solo para personal autorizado",
        "Este módulo maneja información financiera y está restringido por permiso, no solo por menú.",
      ),
      {
        id: "encabezado",
        title: "Las cuatro piezas",
        body: "Cuentas, grupos de cuenta, centros de costo y transacciones. Cada una tiene su pantalla.",
        target: TUTORIAL_TARGETS.tituloPagina,
        placement: "bottom",
      },
      {
        id: "detalle",
        title: "Dónde se registra el movimiento",
        body: "Las ventas y los movimientos se registran en «Transacciones», siempre contra una cuenta existente.",
        target: TUTORIAL_TARGETS.contenidoPrincipal,
        placement: "center",
      },
      intro("cierre", "Orden primero", "Crea las cuentas y los grupos antes de registrar transacciones."),
    ),
  },

  {
    id: "admin-centro-ayuda",
    version: "1.0.0",
    title: "Moverte por el Centro de ayuda",
    description: "Buscar, filtrar, continuar o reiniciar cualquier tutorial del panel.",
    category: "ayuda",
    level: "basico",
    route: "/admin/ayuda",
    roles: ["ADMIN", "SUPER_ADMIN", "CONTADOR"],
    permissions: ["admin:read"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "El Centro de ayuda", "Solo verás los recorridos de los módulos a los que tienes acceso."),
      {
        id: "avance",
        title: "Tu avance general",
        body: "Cuántos tutoriales llevas completados sobre los que tienes disponibles.",
        target: TUTORIAL_TARGETS.centroResumen,
        placement: "bottom",
      },
      {
        id: "buscador",
        title: "Busca por nombre",
        body: "Escribe una palabra clave y el catálogo se filtra al momento.",
        target: TUTORIAL_TARGETS.centroBuscador,
        placement: "bottom",
        interaction: { kind: "escritura", minLength: 2 },
        interactiveTarget: true,
      },
      {
        id: "filtros",
        title: "Filtra por módulo, nivel o estado",
        body: "Útil para repasar solo lo pendiente o revisar un módulo concreto antes de formar a alguien.",
        target: TUTORIAL_TARGETS.centroFiltros,
        placement: "bottom",
      },
      intro("cierre", "Repite sin límite", "Cada tarjeta permite empezar, continuar donde lo dejaste o reiniciar."),
    ),
  },
];
