import { intro, orderedSteps } from "@/features/tutorial/catalog/helpers";
import { navTutorialId, TUTORIAL_TARGETS } from "@/features/tutorial/model/tutorial-targets";
import type { TutorialDefinition } from "@/features/tutorial/model/tutorial.types";

/**
 * Recorridos del portal del paciente.
 *
 * Los pasos que piden una acción real (elegir servicio, escribir un motivo) se detienen
 * ANTES de enviar nada: el tutorial nunca crea una cita en nombre de la persona.
 */
export const PATIENT_TUTORIALS: TutorialDefinition[] = [
  {
    id: "paciente-navegacion",
    version: "1.0.0",
    title: "Tu portal, de un vistazo",
    description: "Qué hay en cada sección del menú y cómo volver siempre a tu resumen.",
    category: "navegacion",
    level: "basico",
    route: "/paciente",
    roles: ["PACIENTE"],
    estimatedMinutes: 3,
    required: true,
    autoStart: true,
    nextTutorialId: "paciente-reservar-cita",
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Bienvenida a tu portal",
        "Aquí gestionas tus citas y accedes a tu contenido. Te mostramos lo esencial en un par de minutos.",
      ),
      {
        id: "resumen",
        title: "Tu resumen",
        body: "Esta pantalla reúne lo importante: tu próxima cita y los accesos que más usas.",
        target: TUTORIAL_TARGETS.tituloPagina,
        placement: "bottom",
      },
      {
        id: "citas",
        title: "Mis citas",
        body: "Consulta el estado de tus citas: próximas, confirmadas y su historial.",
        target: navTutorialId("/paciente/citas"),
        placement: "right",
        // En móvil el menú vive dentro del cajón: el motor lo abre antes de buscar.
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
        errorMessage: "No pudimos abrir el menú de navegación. Ábrelo con el botón ☰ y pulsa «Reintentar».",
      },
      {
        id: "reservar",
        title: "Reservar cita",
        body: "Solicita una nueva cita eligiendo la disponibilidad real de los terapeutas.",
        target: navTutorialId("/paciente/booking"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "premium",
        title: "Contenido premium",
        body: "Recursos exclusivos para suscriptores. Si aún no tienes acceso, puedes solicitarlo desde ahí.",
        target: navTutorialId("/paciente/premium"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "descargables",
        title: "Mis descargables",
        body: "Guías y materiales que puedes consultar y descargar cuando los necesites.",
        target: navTutorialId("/paciente/descargables"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "perfil",
        title: "Tu perfil",
        body: "Actualiza tus datos y preferencias. Tu información se trata con cuidado y privacidad.",
        target: navTutorialId("/paciente/perfil"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "ayuda",
        title: "Centro de ayuda",
        body: "Todos los tutoriales viven aquí: puedes repetirlos o continuar el que dejaste a medias.",
        target: navTutorialId("/paciente/ayuda"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "salir",
        title: "Cerrar sesión",
        body: "Cuando termines, cierra sesión desde aquí, sobre todo si usas un equipo compartido.",
        target: TUTORIAL_TARGETS.cerrarSesion,
        placement: "top",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      intro("cierre", "Ya conoces tu portal", "Sigue con el tutorial de reserva de cita para pedir la tuya paso a paso."),
    ),
  },

  {
    id: "paciente-reservar-cita",
    version: "1.0.0",
    title: "Reservar tu cita",
    description: "El recorrido completo para solicitar una sesión: servicio, terapeuta y horario.",
    category: "citas",
    level: "basico",
    route: "/paciente/booking",
    roles: ["PACIENTE"],
    permissions: ["booking:create"],
    estimatedMinutes: 4,
    required: true,
    prerequisites: ["paciente-navegacion"],
    nextTutorialId: "paciente-mis-citas",
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Vamos a preparar tu cita",
        "Te acompañamos por el formulario. No enviaremos nada por ti: tú decides cuándo confirmar.",
      ),
      {
        id: "formulario",
        title: "El formulario de reserva",
        body: "Aquí eliges qué tipo de sesión necesitas, con quién y cuándo. Todo se valida contra la agenda real.",
        target: "main form",
        placement: "top",
      },
      {
        id: "servicio",
        title: "Elige el servicio",
        body: "Selecciona el tipo de sesión. Cada opción muestra su duración y su precio.",
        target: "#productId",
        placement: "bottom",
        interaction: { kind: "seleccion" },
        interactiveTarget: true,
        hint: "Elige una opción del desplegable para continuar.",
      },
      {
        id: "zona-horaria",
        title: "Confirma tu zona horaria",
        body: "Los horarios se muestran en tu zona. Si viajaste o el sistema la detectó mal, cámbiala aquí.",
        target: "#timezone",
        placement: "bottom",
        interactiveTarget: true,
      },
      {
        id: "horario",
        title: "Elige un horario disponible",
        body: "La disponibilidad se consulta al servidor en ese momento, así que lo que ves es lo que hay libre.",
        target: "main form",
        placement: "top",
        waitForMs: 8000,
      },
      {
        id: "confirmar",
        title: "Cuando estés lista, confirma",
        body: "Este botón envía la solicitud. La revisamos y te avisamos en «Mis citas» cuando quede confirmada.",
        target: 'main form button[type="submit"]',
        placement: "top",
      },
      intro(
        "cierre",
        "Sin prisa",
        "Puedes cerrar el formulario y volver más tarde: nada se envía hasta que pulses el botón de confirmar.",
      ),
    ),
  },

  {
    id: "paciente-mis-citas",
    version: "1.0.0",
    title: "Seguir tus citas",
    description: "Cómo leer el estado de cada cita y qué significa cada etiqueta.",
    category: "citas",
    level: "basico",
    route: "/paciente/citas",
    roles: ["PACIENTE"],
    estimatedMinutes: 2,
    recommended: true,
    steps: orderedSteps(
      intro("bienvenida", "Tus citas en un sitio", "Aquí ves tus sesiones próximas y el historial de las anteriores."),
      {
        id: "encabezado",
        title: "Qué estás viendo",
        body: "El título y la descripción te recuerdan siempre en qué sección estás.",
        target: TUTORIAL_TARGETS.tituloPagina,
        placement: "bottom",
      },
      {
        id: "listado",
        title: "Estado de cada cita",
        body: "Cada fila muestra fecha, modalidad y estado. «Pendiente» significa que aún la estamos confirmando.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Todavía no tienes citas registradas, así que no hay listado que mostrar.",
      },
      intro("cierre", "Listo", "Si necesitas otra sesión, vuelve a «Reservar cita» desde el menú."),
    ),
  },

  {
    id: "paciente-perfil",
    version: "1.0.0",
    title: "Mantener tu perfil al día",
    description: "Dónde actualizar tus datos personales y tu foto.",
    category: "perfil",
    level: "basico",
    route: "/paciente/perfil",
    roles: ["PACIENTE"],
    permissions: ["profile:update"],
    estimatedMinutes: 2,
    recommended: true,
    steps: orderedSteps(
      intro("bienvenida", "Tu perfil", "Tus datos ayudan al equipo a acompañarte mejor. Solo tú y el equipo los veis."),
      {
        id: "formulario",
        title: "Edita tus datos",
        body: "Cambia lo que necesites y guarda al final. Puedes volver a editarlo tantas veces como quieras.",
        target: "main form",
        placement: "top",
      },
      intro("cierre", "Guardado", "Recuerda guardar antes de salir para que los cambios se apliquen."),
    ),
  },

  {
    id: "paciente-descargables",
    version: "1.0.0",
    title: "Usar tus descargables",
    description: "Cómo abrir y descargar las guías y materiales disponibles para ti.",
    category: "contenido",
    level: "basico",
    route: "/paciente/descargables",
    roles: ["PACIENTE"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "Tus materiales", "Guías y recursos que puedes consultar cuando los necesites."),
      {
        id: "listado",
        title: "Cada recurso, su enlace",
        body: "Al descargar se genera un enlace seguro y temporal. El contenido premium requiere suscripción activa.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Aún no hay descargables publicados para tu cuenta.",
      },
      intro("cierre", "Listo", "Si un recurso aparece bloqueado, revisa tu suscripción en «Contenido premium»."),
    ),
  },

  {
    id: "paciente-premium",
    version: "1.0.0",
    title: "Solicitar acceso premium",
    description: "Qué incluye el contenido premium y cómo pedir tu suscripción.",
    category: "contenido",
    level: "basico",
    route: "/paciente/premium",
    roles: ["PACIENTE"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "Contenido premium", "Recursos exclusivos para personas suscritas."),
      {
        id: "solicitud",
        title: "Pide tu acceso",
        body: "Envía la solicitud desde esta pantalla; el equipo la revisa y te avisa cuando quede activa.",
        target: TUTORIAL_TARGETS.contenidoPrincipal,
        placement: "center",
      },
      intro("cierre", "Sin compromiso", "Puedes seguir usando todo el contenido gratuito mientras tanto."),
    ),
  },

  {
    id: "paciente-centro-ayuda",
    version: "1.0.0",
    title: "Moverte por el Centro de ayuda",
    description: "Cómo buscar, filtrar, continuar o repetir cualquier tutorial.",
    category: "ayuda",
    level: "basico",
    route: "/paciente/ayuda",
    roles: ["PACIENTE"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "El Centro de ayuda", "Todos los recorridos de la plataforma están aquí, en un solo sitio."),
      {
        id: "avance",
        title: "Tu avance general",
        body: "Este panel resume cuántos tutoriales has completado sobre los que tienes disponibles.",
        target: TUTORIAL_TARGETS.centroResumen,
        placement: "bottom",
      },
      {
        id: "buscador",
        title: "Busca por nombre",
        body: "Escribe una palabra y el listado se filtra al momento.",
        target: TUTORIAL_TARGETS.centroBuscador,
        placement: "bottom",
        interaction: { kind: "escritura", minLength: 2 },
        interactiveTarget: true,
      },
      {
        id: "filtros",
        title: "Filtra por módulo, nivel o estado",
        body: "Útil cuando solo quieres ver lo pendiente o repasar un módulo concreto.",
        target: TUTORIAL_TARGETS.centroFiltros,
        placement: "bottom",
      },
      intro(
        "cierre",
        "Repite cuando quieras",
        "Cada tarjeta permite empezar, continuar donde lo dejaste o reiniciar el recorrido desde cero.",
      ),
    ),
  },
];
