import { intro, orderedSteps } from "@/features/tutorial/catalog/helpers";
import { navTutorialId, TUTORIAL_TARGETS } from "@/features/tutorial/model/tutorial-targets";
import type { TutorialDefinition } from "@/features/tutorial/model/tutorial.types";

/** Recorridos del portal del terapeuta. */
export const THERAPIST_TUTORIALS: TutorialDefinition[] = [
  {
    id: "terapeuta-navegacion",
    version: "1.0.0",
    title: "Tu portal de terapeuta",
    description: "Las secciones del portal y para qué sirve cada una.",
    category: "navegacion",
    level: "basico",
    route: "/terapeuta",
    roles: ["TERAPEUTA"],
    estimatedMinutes: 3,
    required: true,
    autoStart: true,
    nextTutorialId: "terapeuta-horarios",
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Bienvenido a tu portal",
        "Desde aquí gestionas tu agenda, tus horarios y tu perfil profesional.",
      ),
      {
        id: "resumen",
        title: "Tu resumen",
        body: "La pantalla de inicio reúne el estado de tu agenda y los accesos que más vas a usar.",
        target: TUTORIAL_TARGETS.tituloPagina,
        placement: "bottom",
      },
      {
        id: "agenda",
        title: "Agenda",
        body: "Las sesiones que tienes asignadas, con su estado y su horario.",
        target: navTutorialId("/terapeuta/agenda"),
        placement: "right",
        // En móvil el menú vive dentro del cajón: el motor lo abre antes de buscar.
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
        errorMessage: "No pudimos abrir el menú de navegación. Ábrelo con el botón ☰ y pulsa «Reintentar».",
      },
      {
        id: "horarios",
        title: "Horarios",
        body: "Aquí defines tus franjas disponibles. Es lo que ven los pacientes al reservar.",
        target: navTutorialId("/terapeuta/horarios"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "disponibilidad",
        title: "Disponibilidad",
        body: "Comprueba cómo queda tu disponibilidad real y agenda una sesión para un paciente si hace falta.",
        target: navTutorialId("/terapeuta/booking"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "perfil",
        title: "Tu perfil profesional",
        body: "Tu foto, tu enfoque y tu presentación: es lo que ve el paciente antes de elegirte.",
        target: navTutorialId("/terapeuta/perfil"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      {
        id: "ayuda",
        title: "Centro de ayuda",
        body: "Todos estos recorridos quedan guardados aquí para repetirlos cuando quieras.",
        target: navTutorialId("/terapeuta/ayuda"),
        placement: "right",
        prepare: { target: TUTORIAL_TARGETS.menuMovil },
      },
      intro("cierre", "Listo", "Sigue con el tutorial de horarios: es lo primero que conviene dejar configurado."),
    ),
  },

  {
    id: "terapeuta-horarios",
    version: "1.0.0",
    title: "Configurar tus horarios",
    description: "Definir tus franjas disponibles y bloquear los momentos en los que no atiendes.",
    category: "citas",
    level: "intermedio",
    route: "/terapeuta/horarios",
    roles: ["TERAPEUTA"],
    estimatedMinutes: 4,
    required: true,
    prerequisites: ["terapeuta-navegacion"],
    nextTutorialId: "terapeuta-agenda",
    steps: orderedSteps(
      intro(
        "bienvenida",
        "Tu disponibilidad, en tus términos",
        "Lo que configures aquí es exactamente lo que podrán reservar los pacientes.",
      ),
      {
        id: "encabezado",
        title: "Dónde estás",
        body: "Esta pantalla gestiona tus franjas horarias recurrentes y tus bloqueos puntuales.",
        target: TUTORIAL_TARGETS.tituloPagina,
        placement: "bottom",
      },
      {
        id: "formulario",
        title: "Añade una franja",
        body: "Elige el día y el rango de horas. Puedes crear varias franjas por día.",
        target: "main form",
        placement: "top",
      },
      {
        id: "listado",
        title: "Revisa lo que ya tienes",
        body: "El listado muestra tus franjas activas. Revísalo antes de guardar cambios nuevos.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Todavía no has creado franjas horarias, por eso no hay listado.",
      },
      intro("cierre", "Consejo", "Deja siempre un hueco entre sesiones: la agenda respeta exactamente lo que definas."),
    ),
  },

  {
    id: "terapeuta-agenda",
    version: "1.0.0",
    title: "Trabajar con tu agenda",
    description: "Leer el estado de cada sesión asignada y prepararte para la siguiente.",
    category: "citas",
    level: "basico",
    route: "/terapeuta/agenda",
    roles: ["TERAPEUTA"],
    permissions: ["therapy:read_assigned"],
    estimatedMinutes: 3,
    recommended: true,
    steps: orderedSteps(
      intro("bienvenida", "Tu agenda", "Aquí ves únicamente las sesiones que tienes asignadas."),
      {
        id: "listado",
        title: "Cada fila, una sesión",
        body: "Verás el paciente, la fecha, la modalidad y el estado de la cita.",
        target: TUTORIAL_TARGETS.tablaDatos,
        placement: "top",
        waitForMs: 8000,
        errorMessage: "Aún no tienes sesiones asignadas, así que la agenda está vacía.",
      },
      intro(
        "cierre",
        "Privacidad",
        "Solo ves la información de las personas que tienes asignadas; el resto queda fuera de tu alcance.",
      ),
    ),
  },

  {
    id: "terapeuta-perfil",
    version: "1.0.0",
    title: "Tu perfil profesional",
    description: "Cómo se presenta tu perfil a los pacientes y qué conviene completar.",
    category: "perfil",
    level: "basico",
    route: "/terapeuta/perfil",
    roles: ["TERAPEUTA"],
    permissions: ["profile:update"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "Tu carta de presentación", "Es lo que ve un paciente antes de elegir con quién trabajar."),
      {
        id: "formulario",
        title: "Completa tu información",
        body: "Foto, titular, enfoque y biografía. Cuanto más claro, más fácil es que alguien dé el primer paso.",
        target: "main form",
        placement: "top",
      },
      intro("cierre", "Guarda al terminar", "Los cambios se aplican cuando pulsas guardar al final del formulario."),
    ),
  },

  {
    id: "terapeuta-centro-ayuda",
    version: "1.0.0",
    title: "Moverte por el Centro de ayuda",
    description: "Buscar, filtrar, continuar o repetir cualquier tutorial del portal.",
    category: "ayuda",
    level: "basico",
    route: "/terapeuta/ayuda",
    roles: ["TERAPEUTA"],
    estimatedMinutes: 2,
    steps: orderedSteps(
      intro("bienvenida", "El Centro de ayuda", "Todos los recorridos disponibles para tu rol están aquí."),
      {
        id: "avance",
        title: "Tu avance",
        body: "El panel superior resume cuánto has completado.",
        target: TUTORIAL_TARGETS.centroResumen,
        placement: "bottom",
      },
      {
        id: "buscador",
        title: "Busca un tutorial",
        body: "Escribe una palabra clave para filtrar el catálogo al instante.",
        target: TUTORIAL_TARGETS.centroBuscador,
        placement: "bottom",
        interaction: { kind: "escritura", minLength: 2 },
        interactiveTarget: true,
      },
      intro("cierre", "A tu ritmo", "Puedes reiniciar cualquier recorrido tantas veces como necesites."),
    ),
  },
];
